### ISSUE TITLE
The language server doesn't work

### ISSUE THREAD

**Issue by kamack38** [neomutt/lsp-tree-sitter#3]
When opening a `PKGBUILD` file, the language server exits with exit code `1`.
Here's an LspLog:
```
[ERROR][2023-10-14 13:07:33] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/pkgbuild-language-server"	"stderr"	'Traceback (most recent call last):\n  File "/usr/bin/pkgbuild-language-server", line 8, in <module>\n'
[ERROR][2023-10-14 13:07:33] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/pkgbuild-language-server"	"stderr"	'    sys.exit(main())\n             ^^^^^^\n  File "/usr/lib/python3.11/site-packages/pkgbuild_language_server/__main__.py", line 69, in main\n    from .server import PKGBUILDLanguageServer\n  File "/usr/lib/python3.11/site-packages/pkgbuild_language_server/server.py", line 31, in <module>\n    from pygls.server import LanguageServer\n  File "/usr/lib/python3.11/site-packages/pygls/server.py", line 37, in <module>\n'
[ERROR][2023-10-14 13:07:33] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/pkgbuild-language-server"	"stderr"	'    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType\n  File "/usr/lib/python3.11/site-packages/pygls/lsp/__init__.py", line 38, in <module>\n    from typeguard import check_type\n  File "/usr/lib/python3.11/site-packages/typeguard/__init__.py", line 21, in <module>\n    from ._importhook import ImportHookManager as ImportHookManager\n  File "/usr/lib/python3.11/site-packages/typeguard/_importhook.py", line 22, in <module>\n'
[ERROR][2023-10-14 13:07:33] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/pkgbuild-language-server"	"stderr"	"    from typing_extensions import Buffer\nImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/kamack38/.local/lib/python3.11/site-packages/typing_extensions.py)\n"
```

**Comment by kamack38** [comment]
It was installed via AUR.

**Comment by Freed-Wu** [comment]
I'll take a look.

**Comment by Freed-Wu** [comment]
```python
Traceback (most recent call last):
  File "/usr/bin/pkgbuild-language-server", line 8, in <module>

    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgbuild_language_server/__main__.py", line 69, in main
    from .server import PKGBUILDLanguageServer
  File "/usr/lib/python3.11/site-packages/pkgbuild_language_server/server.py", line 31, in <module>
    from pygls.server import LanguageServer
  File "/usr/lib/python3.11/site-packages/pygls/server.py", line 37, in <module>

    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType
  File "/usr/lib/python3.11/site-packages/pygls/lsp/__init__.py", line 38, in <module>
    from typeguard import check_type
  File "/usr/lib/python3.11/site-packages/typeguard/__init__.py", line 21, in <module>
    from ._importhook import ImportHookManager as ImportHookManager
  File "/usr/lib/python3.11/site-packages/typeguard/_importhook.py", line 22, in <module>

    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/kamack38/.local/lib/python3.11/site-packages/typing_extensions.py)
```

Can you `pip uninstall --break-system-packages typing_extensions`? `/home/kamack38/.local/lib/python3.11/site-packages/typing_extensions.py` overrides `/usr/lib/python3.11/site-packages/typing_extensions.py`
